Update parent to 1.420 so the plug-in will build with Java 7
When building with Java 7 the error java.lang.NoClassDefFoundError:
com/sun/mirror/apt/AnnotationProcessorFactory is thrown.  This was
problem in the maven-hpi-plugin; updating to 1.420 pulls in a recent
enough version of the maven plugin that fixes the error.